server:
  port: 8085
  servlet:
    context-path: /
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${software.datasource.url}
    username: ${software.datasource.username}
    password: ${software.datasource.password}
  application:
    name: systemServiceProvider
  cloud:
    nacos:
      discovery:
        server-addr: nacos://localhost:8848
      config:
        server-addr: nacos://localhost:8848



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      display-name: 'default'
      paths-to-match: '/**'

knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: ?????
  basic:
    enable: false
    username: abc
    password: 123
  insight:
    enable: true
    service-name: boot3
    secret: S6CsnS8AnPVyb8vvChcdXm4R3p6A6KlAISxBg3IIEgk=
    server: http://localhost:10086
    namespace: spring3
logging:
  level:
    com:
      software:
        mapper: debug
        service: info
        controller: info


dubbo:
  application:
    name: systemServiceProvider-dubbo
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848